trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

#- task: VSTest@2
#  inputs:
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    contents: $(System.DefaultWorkingDirectory)/particles.nuspec
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: CopyFiles@2
  inputs:
    contents: $(System.DefaultWorkingDirectory)/Hearn.MonoGame.Particles/bin/Windows/x86/Debug/Hearn.MonoGame.Particles.dll
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishPipelineArtifact@1
  inputs:
    path: $(Build.ArtifactStagingDirectory)
    artifact: drop